services:
  comma-connect-streamer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comma-connect-streamer
    restart: unless-stopped
    ports:
      - "8554:8554"  # RTSP
      - "8888:8888"  # HLS
      - "8889:8889"  # WebRTC
      - "1935:1935"  # RTMP
    environment:
      - DISABLE_COMMA=false
    # Optionally pass config directly:
    # env_file:
    #   - config.conf
    volumes:
      - ./data:/data
      - ./config:/config
    shm_size: '256mb' # Needed for FIFOs in /dev/shm
