# MediaMTX Configuration for Comma Streamer

# Default RTSP port is 8554
# Default RTMP port is 1935
# Default HLS port is 8888
# Default WebRTC port is 8889

paths:
  comma_dashcam:
    # Read from FIFO and push to UDP multicast as H.264 MPEG-TS
    runOnInit: ffmpeg -loglevel error -re -i /dev/shm/new_clip.fifo -c:v libx264 -f mpegts udp://238.0.0.1:1234?pkt_size=1316
    runOnInitRestart: yes
    # MediaMTX consumes the stream from that same UDP address
    source: udp://238.0.0.1:1234

# Allow connections from any IP
rtspAddress: :8554
rtmpAddress: :1935
hlsAddress: :8888
webrtcAddress: :8889
